
Citation
=========

If you use this library either in whole or in part in your analysis, or use any code derived from it, please cite it as:

    |dendropy_citation|

Note that, in the interests of scientific reproducibility, in addition to noting the primary citation for DendroPy as given above in the reference section, you should note in the text of your publications (e.g., in the "Methods" section, or, at the very least, in the "Supplemental Materials" section) the specific version of DendroPy that you used (e.g., "DendroPy version 4.0.0, revision 78e6a63"). You can get useful information about your DendroPy installation by typing "``python -m dendropy``".

If you use or reference any part of this *documentation*, you can cite it as:

    Sukumaran, J. and Mark T. Holder. The DendroPy Phylogenetic Computing Library Documentation. Retrieved |today|, from http://dendropy.org/.


