
.. ###### People ######

.. |js| replace:: Jeet Sukumaran
.. _js: http://www.jeetworks.org/about

.. |mth| replace:: Mark T. Holder
.. _mth: http://people.ku.edu/~mtholder


.. ###### Meta Info ######

.. |sumtrees_citation| replace:: Sukumaran, J. and Mark T. Holder. 2009. *SumTrees: Summarization of Split Support on Phylogenetic Trees. Version 1.0.2*. Part of the *DendroPy Phylogenetic Computation Library Version 2.6.1* (|dendropy_homepage_url|).

.. |dendropy_citation| replace:: Sukumaran, J. and Mark T. Holder. 2009. *DendroPy Phylogenetic Computing Library Version 2.6.1* (|dendropy_homepage_url|).

.. |dendropy_copyright| replace:: **Copyright 2009 Jeet Sukumaran and Mark T. Holder**
