.. ###### DendroPy Locations ######

.. |DendroPy| replace:: DendroPy
.. _DendroPy: http://packages.python.org/DendroPy/
.. |dendropy_homepage_url| replace:: http://packages.python.org/DendroPy/
.. |dendropy_tutorial_url| replace:: http://packages.python.org/DendroPy/tutorial/index.html
.. |dendropy_library_url| replace:: http://packages.python.org/DendroPy/library/index.html
.. |dendropy_download_url| replace:: http://pypi.python.org/pypi/DendroPy
.. |dendropy_public_repo_url| replace:: http://github.com/jeetsukumaran/DendroPy

.. ###### Other Locations ######

.. |Python| replace:: Python
.. _Python: http://www.python.org/

.. |Python26| replace:: Python 2.6
.. _Python 2.6: http://www.python.org/download/releases/2.6/

.. |setuptools| replace:: setuptools
.. _setuptools: http://pypi.python.org/pypi/setuptools

.. |Git| replace:: Git
.. _Git: http://git-scm.com/
