Copyright, License and Warranty
===============================

.. container:: copyrightblock

    The DendroPy project, including all source code, documentation, images, and
    other supporting files and media, either as provided online or otherwise
    distributed, is:

        .. container:: licenseblock

            |dendropy_copyright|

    1.  The DendroPy project source code and associated data files are licensed for
        redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions
        are met:

            *   Redistributions of source code must retain the above copyright
                notice, this list of conditions and the following disclaimer.

            *   Redistributions in binary form must reproduce the above copyright
                notice, this list of conditions and the following disclaimer in the
                documentation and/or other materials provided with the distribution.

            *   The names of its contributors may not be used to endorse or promote
                products derived from this software without specific prior written
                permission.

        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
        AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
        IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
        ARE DISCLAIMED. IN NO EVENT SHALL JEET SUKUMARAN OR MARK T. HOLDER BE
        LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
        CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
        SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
        BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
        WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
        OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
        IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

    2.  All DendroPy documentation, (non-logo) images and other media, as
        provided online or otherwise distributed, can be used in accordance with the
        `Attribution-NonCommercial-ShareAlike 4.0 International License
        <http://creativecommons.org/licenses/by-nc-sa/4.0/>`_ , which allows anyone
        to copy, modify and redistribute modifications of all or part of the DendroPy
        documentation as long as:

            * The license is included with all copies or redistributions.
            * the DendroPy documentation is attributed as the originating document.
            * You must give appropriate credit, provide a link to the license, and
              indicate if changes were made. You may do so in any reasonable
              manner, but not in any way that suggests the licensor endorses you or
              your use.
            * You may not use the material for commercial purposes.
            * If you remix, transform, or build upon the material, you must
              distribute your contributions under the same license as the original.

    3.  The `DendroPy logo <_static/dendropy.png>`_  can be used and reproduced
        freely only to identify, advertise, or otherwise denote association
        or usage of the DendroPy library.
