Copyright, License and Warranty
===============================

DendroPy
--------

The |DendroPy|_ library and the `DendroPy logo <_static/dendropy.png>`_ are:

    |dendropy_copyright|.

The |DendroPy|_ library is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the
License, or (at your option) any later version.
The |DendroPy|_ library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
the `GNU General
Public License <http://www.gnu.org/licenses/gpl.html>`_ for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Usage of the `DendroPy logo <_static/dendropy.png>`_, either in whole or in part, is restricted to the authors of the |DendroPy|_ library, with limited usage granted to third parties exclusively for the acknowledgement of, or for linking or referring to, the |DendroPy|_ library.

Supporting Components
---------------------

The ElementTree XML-parsing toolkit bundled with DendroPy is Copyright (c) 1999-2005 by Fredrik Lundh:

    Permission to use, copy, modify, and distribute this software and its associated documentation for any purpose and without fee is hereby granted, provided that the above copyright notice appears in all copies, and that both that copyright notice and this permission notice appear in supporting documentation, and that the name of Secret Labs AB or the author not be used in advertising or publicity pertaining to distribution of the software without specific, written prior permission.
