
Citation
=========

If you use version 5 of this library either in whole or in part in your research, or use any code derived from it, please cite it as:

    |dendropy_citation|

For BibTex users:

.. code-block:: bibtex

  @misc{dendropy5,
    doi = {10.21105/joss.06943},
    url = {https://doi.org/10.21105/joss.06943},
    year = {2024},
  publisher = {The Open Journal},
    volume = {9},
    number = {101},
    pages = {6943},
    author = {Matthew Andres Moreno and Mark T. Holder and Jeet Sukumaran},
    title = {DendroPy 5: a mature Python library for phylogenetic computing},
    journal = {Journal of Open Source Software}
  }

Note that, in the interests of scientific reproducibility, in addition to noting the primary citation for DendroPy as given above in the reference section, you should note in the text of your publications (e.g., in the "Methods" section, or, at the very least, in the "Supplemental Materials" section) the specific version of DendroPy that you used (e.g., "DendroPy version 4.0.0, revision 78e6a63"). You can get useful information about your DendroPy installation by typing "``python -m dendropy``".

Earlier DendroPy versions can be cited as:

      Sukumaran, J. and M. T. Holder. 2010. DendroPy: a Python library for phylogenetic computing. Bioinformatics 26: 1569-1571. https://doi.org/10.1093/bioinformatics/btq228

If you use or reference any part of this *documentation*, you can cite it as:

    Sukumaran, J. and Mark T. Holder. The DendroPy Phylogenetic Computing Library Documentation. Retrieved |today|, from https://jeetsukumaran.github.io/DendroPy/.

Consider also leaving a `star on GitHub <https://github.com/jeetsukumaran/DendroPy/stargazers>`_!
