
Citation
=========

If you use version 5 of this library either in whole or in part in your research, or use any code derived from it, please cite it as:

    |dendropy_citation|

.. code-block:: bibtex

      @misc{dendropy5,
         title = {DendroPy 5: a mature Python library for phylogenetic computing},
         author = {Moreno,  Matthew Andres and Sukumaran,  Jeet and Holder,  Mark T.},
         year = {2024},
         keywords = {Populations and Evolution (q-bio.PE),  FOS: Biological sciences,  FOS: Biological sciences},
         publisher = {arXiv},
         doi = {10.48550/ARXIV.2405.14120},
         url = {https://arxiv.org/abs/2405.14120},
         copyright = {arXiv.org perpetual, non-exclusive license}
      }

Note that, in the interests of scientific reproducibility, in addition to noting the primary citation for DendroPy as given above in the reference section, you should note in the text of your publications (e.g., in the "Methods" section, or, at the very least, in the "Supplemental Materials" section) the specific version of DendroPy that you used (e.g., "DendroPy version 4.0.0, revision 78e6a63"). You can get useful information about your DendroPy installation by typing "``python -m dendropy``".

Earlier DendroPy versions can be cited as:

      Sukumaran, J. and M. T. Holder. 2010. DendroPy: a Python library for phylogenetic computing. Bioinformatics 26: 1569-1571. https://doi.org/10.1093/bioinformatics/btq228

If you use or reference any part of this *documentation*, you can cite it as:

    Sukumaran, J. and Mark T. Holder. The DendroPy Phylogenetic Computing Library Documentation. Retrieved |today|, from https://jeetsukumaran.github.io/DendroPy/.

Consider also leaving a `star on GitHub <https://github.com/jeetsukumaran/DendroPy/stargazers>`_!
