Copyright, License, and Warranty
===============================

.. container:: copyrightblock

    |dendropy_copyright|

    The DendroPy project is distributed under the BSD 3-clause license except where otherwise explicitly noted.
    Refer to our `license <https://github.com/jeetsukumaran/DendroPy/blob/main/LICENSE.rst>`_ and `notices <https://github.com/jeetsukumaran/DendroPy/blob/main/NOTICES.rst>`_ for details.
