s = d.as_string(
        schema='nexus',
        simple=False,
        suppress_taxa_blocks=None,
        suppress_block_titles=None,
        file_comments=[],
        preamble_blocks=[],
        supplemental_blocks=[],
        allow_multiline_comments=True,
        continuous_character_state_value_format_fn=None,
        discrete_character_state_value_format_fn=None,
        unquoted_underscores=False,
        preserve_spaces=False,
        suppress_annotations=False,
        annotations_as_nhx=False,
        suppress_item_comments=False,
        real_value_format_specifier='',
        ignore_unrecognized_keyword_arguments=False,
        )

